### ISSUE TITLE
Use a more lightweight library for slugs

### ISSUE THREAD

**Issue by richardneililagan** [richardneililagan/base16-builder-node#1]
The current slug library (`slug@0.9.1`) seems to be too heavy and overarching for the purposes of this library --- it installs and builds unicode definitions. While that is all appreciated and probably sides with caution, using a more straightforward slug library (or maybe even just rolling out our own logic that performs the necessary algorithm) is much more practical.

**Comment by joshgoebel** [comment]
Suggestion of specific libraries?

**Comment by joshgoebel** [comment]
This is internal now.
