### ISSUE TITLE
Non-ASCII characters are lost in slugs

### ISSUE THREAD

**Issue by joshgoebel** [richardneililagan/base16-builder-node#10]
From: https://github.com/base16-project/base16-builder-node/issues/9

In any case, special characters in the name of some schemes seem to be dropped in the name of the generated theme files such as [Rosé Pine](https://github.com/base16-project/base16-schemes/blob/main/rose-pine.yaml) which seems to simply build to [base16-ros-pine](https://github.com/edunfelt/base16-pyradio/blob/main/themes/base16-ros-pine.pyradio-theme).

**Comment by joshgoebel** [comment]
@belak How does the node builder handle this?  I'm just dropping anything that doesn't match `\W` to generate slugs... it seems perhaps a better downsamples to ASCII is called for... or should we just spew out unicode names to the disk?

**Comment by belak** [comment]
> @belak How does the node builder handle this? I'm just dropping anything that doesn't match `\W` to generate slugs... it seems perhaps a better downsamples to ASCII is called for... or should we just spew out unicode names to the disk?

The spec says to use the filename without the `.yaml` extension. I believe that's what the Go builder does.

**Comment by joshgoebel** [comment]
This issue is resolved by switching to the spec behavior of slugifying filename.
