### ISSUE TITLE
All forward slashes are represented by &#x2F; in the rendered Moustache templates

### ISSUE THREAD

**Issue by jordiorlando** [richardneililagan/base16-builder-node#2]
It seems as though forward slashes are being escaped as `&#x2F;` in the rendered themes. For example, `{{scheme-author}}` gets resolved to `Jan T. Sott (http:&#x2F;&#x2F;github.com&#x2F;idleberg)` instead of `Jan T. Sott (http://github.com/idleberg)`.

**Comment by joshgoebel** [comment]
@0xdec Just tell mustache not to escape with triple brackets.

```
/*!
  Theme: {{{scheme-name}}}
  Author: {{{scheme-author}}}

  This theme was auto-generated from {{scheme-slug}} by Highlight.js Base16
  template builder.
*/
```

**Comment by jordiorlando** [comment]
Hahaha, thank you

**Comment by joshgoebel** [comment]
@0xdec Issue resolved then?

**Comment by jordiorlando** [comment]
I don't know, I haven't used this for 4 years. Sounds like it would work.

**Comment by joshgoebel** [comment]
Works for me as I had the same problem.
