### ISSUE TITLE
New Maintainer?

### ISSUE THREAD

**Issue by joshgoebel** [richardneililagan/base16-builder-node#4]
@richardneililagan I'm willing to take over this project and maintain my fork (I don't expect it to require much effort) if you no longer have time or interest. I did open a PR to bring things up-to-date since 5 years ago.  Let me know.  I think it would be as simple as updating the Base16 repos to point to the new location.

**Comment by richardneililagan** [comment]
Hey @joshgoebel,

Happy to turn over ownership of the project to you if you're keen. 
Haven't been able to keep on top of it admittedly, so it'd most probably be in better hands with you.

**Comment by joshgoebel** [comment]
- Shall I simply update the Base16 repo to point to my fork then?
- Should we update the README here to redirect?
- Should we keep both repos updated side-by-side for a short time? (if so adding me as a collab here would help, easy enough to push to both)
- Could you add me (`joshgoebel`) as a collaborator on `npm` so I can push new versions out?
- @belak Any objection to this repo migrating into the new base16 organization if/when we get that setup?

Thoughts?

**Comment by richardneililagan** [comment]
I was actually thinking of transferring the repo ownership itself (as in using the Github process :p).
I did try that earlier, but it didn't push through because you already had a fork with the same name. Thought that was a bit of a weird constraint.

Would you prefer it that way?

**Comment by joshgoebel** [comment]
Oh that's fun... haven't done that before I don't think.

I renamed my fork to `base16-builder-node.renamed`... does that let you transfer now?

> Thought that was a bit of a weird constraint.

Yeah seems it should let you rename + transfer... but *shrugs*.

**Comment by belak** [comment]
@joshgoebel My usual process for the base16 repo is to change it if the current maintainer confirms the changes (this issue would count), or there's a delay of a month or more. I'm happy to push an update.

Normally, transferring the repo is ideal because it keeps issues/PRs and ensures that the primary repo doesn't display "forked from someuser/somerepo".

**Comment by joshgoebel** [comment]
> Normally, transferring the repo is ideal

Yeah, I'm fine with that if it works now that I renamed. :)  

Did you miss the key question:

> @belak Any objection to this repo migrating into the new base16 organization if/when we get that setup?

If we have a `@base16-project` in the future I'd honestly prefer this just live there long-term if that was possible. (slightly better visibility, etc)

**Comment by belak** [comment]
> > @belak Any objection to this repo migrating into the new base16 organization if/when we get that setup?
> 
> If we have a `@base16-project` in the future I'd honestly prefer this just live there long-term if that was possible. (slightly better visibility, etc)

Yeah, that works for me. Sorry, I thought I replied to that but it must have just been in my mind.

**Comment by joshgoebel** [comment]
@richardneililagan Were you going to try to transfer the whole repo now that I renamed my fork?

**Comment by joshgoebel** [comment]
@richardneililagan Ping.
