### ISSUE TITLE
`sources.yaml` needs to be updated

### ISSUE THREAD

**Issue by JamyGolden** [richardneililagan/base16-builder-node#5]
https://github.com/base16-project/base16-builder-node/blob/master/lib/sources.yaml need to be updated and pointed to the base16-project repos, but those haven't yet been created. @belak what is the plan on doing that? Is it just a matter of creating the repo and bringing across the git history or is there more to it?

**Comment by belak** [comment]
Spec 0.10.0 drops those as a concept. All the current schemes were copied into https://github.com/base16-project/base16-schemes and builders are encouraged to focus on building a single templated repo at a time, removing the need for the `*-source` repos. The goal of that change was to remove the need for builders to do complicated git operations and simplify their focus.

That was one of the reasons I merged spec 0.10.0 when moving over to the base16-project org, so we wouldn't need those repos.

**Comment by JamyGolden** [comment]
Makes sense, thanks :+1:

**Comment by joshgoebel** [comment]
Wait, I need to read 0.10.... so now we don't futz with git at all?  If they just need themes then I'd prefer to just have instructions telling them to how to fetch/update schemes from git manually and let the builder do ONLY building.

**Comment by belak** [comment]
Pretty much. I really wanted to simplify the complicated repo setup with 0.10.0 - the best way forward would be to either bundle the schemes with a release or provide a way to download them, but it's limited to just the schemes repo now (not the source repo plus separate repos for every single set of schemes and the same for templates). You could have it clone the repo to a common location for convenience.

Most template maintainers only want to deal with one template - there's no need to clone *all* the templates just to build their project.

It also has the nice side-effect of simplifying builders.

**Comment by joshgoebel** [comment]
> Most template maintainers only want to deal with one template - there's no need to clone all the templates just to build their project.

Fully agree with this one.
