### ISSUE TITLE
Maintainers outside of base16-project

### ISSUE THREAD

**Issue by JamyGolden** [richardneililagan/base16-builder-node#6]
@richardneililagan you have write access to this repo but aren't on the http://github.com/base16-project team. Should I add you to the team (as a maintainer) or remove you from the project? I'm not sure if you're aware of base16-project or the changes happening to base16 in general? Additionally, if you'd like to be part of the team and maintain different projects, let me know which ones and I can add you ad a maintainer there.

**Comment by richardneililagan** [comment]
@JamyGolden remove would probably be best at this point --- I'll reconsider jumping in once I can more confidently put in the time for it. Thanks for bringing it up.

**Comment by JamyGolden** [comment]
Ok sounds good!
